version: "3"

services:
    payment-service:
        image: webdevops/php:8.0
        ports:
            - 8083:80
        working_dir: /app
        environment: 
            - WEB_DOCUMENT_ROOT=/app/public
            - PHP_MEMORY_LIMIT=512M
            - PHP_MAX_EXECUTION_TIME=30
            - PHP_POST_MAX_SIZE=20M
            - PHP_UPLOAD_MAX_FILESIZE=20M
        volumes:
            - './app:/app'
    payment_DB:
        image: postgres:11.12
        environment:
            POSTGRES_DB: payment
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        volumes:
            - payment-db-data:/var/lib/postgresql/data/
        ports:
            - "8330:5432"
        command: ["postgres", "-c", "logging_collector=on", "-c", "log_destination=stderr", "-c", "max_connections=10000"]

    payment_test_DB:
        image: postgres:11.12
        environment:
            POSTGRES_DB: payment
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        volumes:
            - payment-test-db-data:/var/lib/postgresql/data/
        ports:
            - "8331:5432"
        command: ["postgres", "-c", "logging_collector=on", "-c", "log_destination=stderr", "-c", "max_connections=10000"]

volumes:
    payment-db-data:
    payment-test-db-data: